### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by Fahaxikiii** [FYWinds/takker#18]
C:\Users\Administrator\Desktop\takker-master>poetry run bot.py

OSError

[WinError 193] %1 不是有效的 Win32 应用程序。

at c:\users\administrator\appdata\local\programs\python\python39\lib\subproces
s.py:1416 in _execute_child
1412│ sys.audit("subprocess.Popen", executable, args, cwd, en
v)
1413│
1414│ # Start the process
1415│ try:
→ 1416│ hp, ht, pid, tid = _winapi.CreateProcess(executabl
e, args,
1417│ # no special security
1418│ None, None,
1419│ int(not close_fds),
1420│ creationflags,

C:\Users\Administrator\Desktop\takker-master>

**Comment by FYWinds** [comment]
> C:\Users\Administrator\Desktop\takker-master>poetry run bot.py

`poetry run xxx`是在poetry的shell环境内执行xxx指令
所以你需要的是`poetry run python bot.py`

**Comment by Fahaxikiii** [comment]
> > C:\Users\Administrator\Desktop\takker-master>poetry run bot.py
> 
> `poetry run xxx`是在poetry的shell环境内执行xxx指令 所以你需要的是`poetry run python bot.py`

好的，poetry版本是1.1.12吧，我用的离线下载方式，python get-poetry.py --file poetry-1.1.12-win32.tar.gz

**Comment by FYWinds** [comment]
poetry版本没有什么影响的

**Comment by Fahaxikiii** [comment]
> poetry版本没有什么影响的
好的，感谢！
