### ISSUE TITLE
安装依赖相关的问题

### ISSUE THREAD

**Issue by Fahaxikiii** [FYWinds/takker#19]
![QQ图片20211207193528](https://user-images.githubusercontent.com/93320886/145022309-087bf914-fafc-43d7-97cc-cad29489fe30.png)
安装完部分依赖后总是会出现这种情况是怎么回事。

**Comment by FYWinds** [comment]
检查你所使用的源和网络环境，这是下载下来的wheel文件检查sha失败的报错

**Comment by Fahaxikiii** [comment]
> 检查你所使用的源和网络环境，这是下载下来的wheel文件检查sha失败的报错

源怎么看，QAQ。

**Comment by Fahaxikiii** [comment]
他一会儿这个文件报错，重新部署后一会儿另外一个又报错而这个又不报错。太难了。

**Comment by Fahaxikiii** [comment]
> 检查你所使用的源和网络环境，这是下载下来的wheel文件检查sha失败的报错

pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple换这个可以吗

**Comment by FYWinds** [comment]
清华源/阿里源等不推荐
建议还是使用pypi.org官方源
如果网络环境没什么限制的话，建议poetry也更新一下

**Comment by Fahaxikiii** [comment]
> 
睡尼玛傻逼 21:27:09
清华：https://pypi.tuna.tsinghua.edu.cn/simple
阿里云：http://mirrors.aliyun.com/pypi/simple/
中国科技大学： https://pypi.mirrors.ustc.edu.cn/simple/
豆瓣：http://pypi.douban.com/simple/

睡尼玛傻逼 21:28:21
腾讯云：
http://mirrors.tencentyun.com/pypi/simple/
官方源：
https://pypi.org/simple/
这是我查到的源，试了一遍均有报错。

官方源的scipy==1.6.1；matplotlib==3.4.3；imageio-ffmpeg==0.4.5有报错。能否本地下载然后安装，或者说改变依赖文件所描述的SHA256值使其与官方源文件SHA256值相同。

**Comment by FYWinds** [comment]
怪事，你把poetry.lock文件删了，然后使用最新版poetry并且使用官方源下载试试（

实在不行就poetry shell然后pip install 每个没装上的包

**Comment by Fahaxikiii** [comment]
> 怪事，你把poetry.lock文件删了，然后使用最新版poetry并且使用官方源下载试试（
> 
> 实在不行就poetry shell然后pip install 每个没装上的包

好的，麻烦您了。
