### ISSUE TITLE
询问，超级用户名单应该怎么填写

### ISSUE THREAD

**Issue by Fahaxikiii** [FYWinds/takker#21]
SUPERUSERS: List[Union[int, str]] = ["12345678", "0", "0", 3116556127]  
群聊发送perm list一直回复参数错误
example： SUPERUSERS: List[Union[int, str]] = ["12345678", "0", "0", 12345678]  # 超级用户名单

**Comment by FYWinds** [comment]
perm list参数错误指的是指令的参数错误，请查看`/help perm_control`

正确用法为
`perm list -u` 查看用户权限列表
`perm list -p` 查看插件权限列表
`perm list -g` 查看群组权限列表

**Comment by Fahaxikiii** [comment]
> perm list参数错误指的是指令的参数错误，请查看`/help perm_control`
> 
> 正确用法为 `perm list -u` 查看用户权限列表 `perm list -p` 查看插件权限列表 `perm list -g` 查看群组权限列表

好的，谢谢
