### ISSUE TITLE
虚拟环境并启动Bot出错

### ISSUE THREAD

**Issue by LuciTc** [FYWinds/takker#5]
在tmux用了python -m poetry shell后出现错误。
Spawning shell within /root/.cache/pypoetry/virtualenvs/takker-reborn-NcqX0U7w-py3.9
root@ubuntu-2004-tt:~/qbot/takker# . /root/.cache/pypoetry/virtualenvs/takker-reborn-NcqX0U7w-py3.9/bin/activate
并且后面命令行前面带有(takker-reborn-NcqX0U7w-py3.9)。

**Comment by FYWinds** [comment]
此为Poetry启用虚拟环境的正常输出内容，告知你执行了`. /root/.cache/pypoetry/virtualenvs/takker-reborn-NcqX0U7w-py3.9/bin/activate`并且进入了`(takker-reborn-NcqX0U7w-py3.9)`的虚拟环境
